#!/usr/bin/env bash

echo Скрипт для восстановления БД Postgres.
read -p "Имя базы: " db
psql -U postgres -l | awk '{print $1}' | grep -w $db > /dev/null
  while [ $? != 0 ]
  do echo "Неверное имя БД" 
  read -p "Имя базы: " db
  psql -U postgres -l | awk '{print $1}' | grep $db > /dev/null
  done
read -p "Имя бэкапа: " bckp
dropdb -U postgres $db; createdb -U postgres $db;
pg_restore -U postgres -d $db -j 5 /backup/db/$bckp
