#!/usr/bin/env bash

echo Скрипт для восстановления БД Postgres.
read -p "Имя базы: " db
psql -U postgres -l | awk '{print $1}' | grep -w $db > /dev/null
  while [ $? != 0 ]
  do echo "Неверное имя БД" 
  read -p "Имя базы: " db
  psql -U postgres -l | awk '{print $1}' | grep $db > /dev/null
  done
  
  
  
  
  
  
  
  psql -U postgres -d postgres -c "select client_port from pg_stat_activity;" | tail -n +3 | awk 'NF > 0 {print $1}' | head -n -1   - проверка количества соединений через клиентские порты.
