#!/usr/bin/env bash

echo -e "Скрипт для восстановления бэкапов PostgreSQL\nБаза уже существует?: "

select option in Да Нет; do 
	case $option in 
		Да)
			psql -U postgres -c "SELECT datname FROM pg_database;" | tail -n +3
			echo -e "ВНИМАНИЕ!!!При восстановлении базы, текущая версия будет удалена!!!\n"
			read -p "Введите имя базы: " db
			psql -U postgres -l | awk '{print $1}' | grep -w $db > /dev/null
			while [ $? != 0 ]
				do echo "Неверное имя БД" 
				read -p "Введите имя базы: " db
				psql -U postgres -l | awk '{print $1}' | grep $db > /dev/null
			done
			ls /backup/db/
			read -p "Введите имя бэкапа: " bckp
			dropdb -U postgres $db; createdb -U postgres $db;
			pg_restore -U postgres -d $db -j 5 /backup/db/$bckp.gz
			break
			;;
		Нет)
			echo "Создайте базу через оснастку 1С и запустите скрипт заново ¯\_( ͡• ͜ʖ ͡•)_/¯ "
			break
			;;
	esac
done
